// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

using BookStore.Shared.Models;

#nullable enable annotations

namespace BookStore.Client
{
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "1.7.1.0")]
    public partial interface IGetBooksEndpoint
    {
        [Headers("Accept: application/json")]
        [Get("/api/books")]
        Task<PagedListDtoOfBookDto> Execute([Query, AliasAs("Page")] int? page, [Query, AliasAs("PageSize")] int? pageSize, [Query] string search, [Header("api-version")] object api_version, [Header("Accept-Language")] object accept_Language, [Header("X-Correlation-ID")] object x_Correlation_ID, [Header("X-Causation-ID")] object x_Causation_ID, CancellationToken cancellationToken = default);
    }

}