// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

using BookStore.Shared.Models;

#nullable enable annotations

namespace BookStore.Client
{
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "1.7.1.0")]
    public partial interface IUpdateBookEndpoint
    {
        [Headers("Content-Type: application/json")]
        [Put("/api/admin/books/{id}")]
        Task Execute(System.Guid id, [Body] UpdateBookRequest body, [Header("api-version")] object api_version, [Header("Accept-Language")] object accept_Language, [Header("X-Correlation-ID")] object x_Correlation_ID, [Header("X-Causation-ID")] object x_Causation_ID, CancellationToken cancellationToken = default);
    }

}