// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

using BookStore.Shared.Models;

#nullable enable annotations

namespace BookStore.Client
{
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "1.7.1.0")]
    public partial interface ICreatePublisherEndpoint
    {
        [Headers("Content-Type: application/json")]
        [Post("/api/admin/publishers")]
        Task Execute([Body] CreatePublisherRequest body, [Header("api-version")] string api_version, [Header("Accept-Language")] string accept_Language, [Header("X-Correlation-ID")] string? x_Correlation_ID = null, [Header("X-Causation-ID")] string? x_Causation_ID = null, CancellationToken cancellationToken = default);
    }

}