// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

using BookStore.Shared.Models;

#nullable enable annotations

namespace BookStore.Client
{
    public partial interface ICreateBookEndpoint
    {
        [Headers("Content-Type: application/json")]
        [Post("/api/admin/books")]
        Task CreateBookAsync([Body] CreateBookRequest body, CancellationToken cancellationToken = default);

        [Headers("Content-Type: application/json")]
        [Post("/api/admin/books")]
        Task<IApiResponse> CreateBookWithResponseAsync([Body] CreateBookRequest body, CancellationToken cancellationToken = default);
    }

}