// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

using BookStore.Shared.Models;

#nullable enable annotations

namespace BookStore.Client
{
    
    public partial interface ICreateCategoryEndpoint
    {
        [Headers("Content-Type: application/json")]
        [Post("/api/admin/categories")]
        Task CreateCategoryAsync([Body] CreateCategoryRequest body, CancellationToken cancellationToken = default);

        [Headers("Content-Type: application/json")]
        [Post("/api/admin/categories")]
        Task<ApiResponse<CategoryDto>> CreateCategoryWithResponseAsync([Body] CreateCategoryRequest body, CancellationToken cancellationToken = default);
    }

}