// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

using BookStore.Shared.Models;

#nullable enable annotations

namespace BookStore.Client
{
    
    public partial interface IGetAuthorsEndpoint
    {
        [Headers("Accept: application/json")]
        [Get("/api/authors")]
        Task<PagedListDto<AuthorDto>> GetAuthorsAsync([Query, AliasAs("Page")] int? page, [Query, AliasAs("PageSize")] int? pageSize, CancellationToken cancellationToken = default);
    }

}