// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

using BookStore.Shared.Models;

#nullable enable annotations

namespace BookStore.Client
{
    
    public partial interface IGetProjectionStatusEndpoint
    {
        [Headers("Accept: application/json")]
        [Get("/api/admin/projections/status")]
        Task<ProjectionStatusResponse> Execute(CancellationToken cancellationToken = default);
    }

}