// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

using BookStore.Shared.Models;

#nullable enable annotations

namespace BookStore.Client
{
    
    public partial interface IGetAuthorEndpoint
    {
        [Headers("Accept: application/json")]
        [Get("/api/authors/{id}")]
        Task<AuthorDto> GetAuthorAsync(System.Guid id, [Header("Accept-Language")] string? acceptLanguage = default, CancellationToken cancellationToken = default);
    }

}