// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

using BookStore.Shared.Models;

#nullable enable annotations

namespace BookStore.Client
{
    
    public partial interface IGetCategoryEndpoint
    {
        [Headers("Content-Type: application/json")]
        [Get("/api/categories/{id}")]
        Task<CategoryDto> GetCategoryAsync(System.Guid id, [Header("If-None-Match")] string? ifNoneMatch = default, [Header("Accept-Language")] string? acceptLanguage = default, CancellationToken cancellationToken = default);

        [Headers("Content-Type: application/json")]
        [Get("/api/categories/{id}")]
        Task<IApiResponse<CategoryDto>> GetCategoryWithResponseAsync(System.Guid id, [Header("If-None-Match")] string? ifNoneMatch = default, [Header("Accept-Language")] string? acceptLanguage = default, CancellationToken cancellationToken = default);
    }

}