// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

using BookStore.Shared.Models;

#nullable enable annotations

namespace BookStore.Client
{
    
    public partial interface IGetPublisherEndpoint
    {
        [Headers("Content-Type: application/json")]
        [Get("/api/publishers/{id}")]
        Task<PublisherDto> GetPublisherAsync(System.Guid id, [Header("If-None-Match")] string? ifNoneMatch = default, CancellationToken cancellationToken = default);

        [Headers("Content-Type: application/json")]
        [Get("/api/publishers/{id}")]
        Task<IApiResponse<PublisherDto>> GetPublisherWithResponseAsync(System.Guid id, [Header("If-None-Match")] string? ifNoneMatch = default, CancellationToken cancellationToken = default);
    }

}