// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

using BookStore.Shared.Models;

#nullable enable annotations

namespace BookStore.Client
{
    
    public partial interface IGetCategoriesEndpoint
    {
        [Headers("Accept: application/json")]
        [Get("/api/categories")]
        Task<PagedListDto<CategoryDto>> GetCategoriesAsync([Query, AliasAs("Page")] int? page, [Query, AliasAs("PageSize")] int? pageSize, [Query] string? sortBy, [Query] string? sortOrder, CancellationToken cancellationToken = default);
    }

}