// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

using BookStore.Shared.Models;

#nullable enable annotations

namespace BookStore.Client
{
    
    public partial interface IRestoreCategoryEndpoint
    {
        [Post("/api/admin/categories/{id}/restore")]
        Task RestoreCategoryAsync(System.Guid id, [Header("If-Match")] string? etag = null, CancellationToken cancellationToken = default);

        [Post("/api/admin/categories/{id}/restore")]
        Task<IApiResponse> RestoreCategoryWithResponseAsync(System.Guid id, [Header("If-Match")] string? etag = null, CancellationToken cancellationToken = default);
    }

}