// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

using BookStore.Shared.Models;

#nullable enable annotations

namespace BookStore.Client
{
    
    public partial interface IRestoreAuthorEndpoint
    {
        [Post("/api/admin/authors/{id}/restore")]
        Task Execute(System.Guid id, CancellationToken cancellationToken = default);
    }

}