// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

using BookStore.Shared.Models;

#nullable enable annotations

namespace BookStore.Client
{
    
    public partial interface ISoftDeleteCategoryEndpoint
    {
        [Delete("/api/admin/categories/{id}")]
        Task Execute(System.Guid id, CancellationToken cancellationToken = default);
    }

}