// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

using BookStore.Shared.Models;

#nullable enable annotations

namespace BookStore.Client
{
    
    public partial interface IUpdateCategoryEndpoint
    {
        [Headers("Content-Type: application/json")]
        [Put("/api/admin/categories/{id}")]
        Task UpdateCategoryAsync(System.Guid id, [Body] UpdateCategoryRequest body, CancellationToken cancellationToken = default);
    }

}