// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

using BookStore.Shared.Models;

#nullable enable annotations

namespace BookStore.Client
{
    
    public partial interface IUpdatePublisherEndpoint
    {
        [Headers("Content-Type: application/json")]
        [Put("/api/admin/publishers/{id}")]
        Task UpdatePublisherAsync(System.Guid id, [Body] UpdatePublisherRequest body, [Header("If-Match")] string? etag = null, CancellationToken cancellationToken = default);

        [Headers("Content-Type: application/json")]
        [Put("/api/admin/publishers/{id}")]
        Task<IApiResponse> UpdatePublisherWithResponseAsync(System.Guid id, [Body] UpdatePublisherRequest body, [Header("If-Match")] string? etag = null, CancellationToken cancellationToken = default);
    }

}