// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

using BookStore.Shared.Models;

#nullable enable annotations

namespace BookStore.Client
{
    
    public partial interface IUpdateBookEndpoint
    {
        [Headers("Content-Type: application/json")]
        [Put("/api/admin/books/{id}")]
        Task UpdateBookAsync(System.Guid id, [Body] UpdateBookRequest body, CancellationToken cancellationToken = default);
    }

}