// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

using BookStore.Shared.Models;

#nullable enable annotations

namespace BookStore.Client
{
    
    public partial interface IUploadBookCoverEndpoint
    {
        [Multipart]
        [Post("/api/admin/books/{id}/cover")]
        Task UploadBookCoverAsync(System.Guid id, StreamPart file, CancellationToken cancellationToken = default);
    }

}